
[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
final_project = { path = "../game", optional = true }

[features]
default = ["final_project"]
dylib = ["fyrox/dylib"]
